### ISSUE TITLE
Issue 1 Seleccionar y cargar la base de datos

### ISSUE THREAD

**Issue by nelsonalejandrov** [prope-2021-gh-classroom/practica-final-verano-2021-nelsonalejandrov#2]
Podemos investigar de alguna de estas fuentes:
[Datos CDMX](https://datos.cdmx.gob.mx/dataset/)
[Datos de Amazon AWS](https://registry.opendata.aws/)
[Google Trends](https://trends.google.com/trends/)
[Kaggle](https://www.kaggle.com/)

**Comment by nelsonalejandrov** [comment]
Decidimos usar una base de datos de calidad de vino. Esta fue descargada de la plataforma Kaggle:
[Redwine quality.](https://www.kaggle.com/uciml/red-wine-quality-cortez-et-al-2009)

**Comment by CAMM961001** [comment]
De acuerdo con la selección de la base de datos!
